### ISSUE TITLE
Parsing error when using ternary operator in Formula/Label

### ISSUE THREAD

**Issue by HansvdLaan** [prismmodelchecker/prism#104]
Whenever I try to use a ternary operator in a formula/label, I'm presented with a parsing error:

```

const double default_probability = 0.5;
formula: conditional_probability = (x=8 ? 0 : default_probability);

module test

    x : [0..8] init 0;

    [] true ->
    conditional_probability*0.1 : (x' = min(x + 1, 8))
    + conditional_probability*0.9 : true
    + 1 - conditional_probability: true;

endmodule

Parsing model file ".\tertiary_operator_in_formula.prism"...
Error: Syntax error (":", line 6, column 8). 

```

Using a ternary operator in a probability works:
```

const double default_probability = 0.5;

module test

    x : [0..8] init 0;

    [] true ->
    (x=8 ? 0 : default_probability)*0.1 : (x' = min(x + 1, 8))
    + (x=8 ? 0 : default_probability)*0.9 : true
    + 1 - (x=8 ? 0 : default_probability): true;

endmodule

```

**Comment by kleinj** [comment]
Hi,

the issue here is the extra `:` in `formula:`. If you remove that, everything parses fine (see [here](http://www.prismmodelchecker.org/manual/ThePRISMLanguage/FormulasAndLabels) for the syntax). For these kinds of problems, the PRISM GUI editor is quite useful as it will highlight (most of the time) the location of the syntax error.

Cheers,
Joachim

**Comment by HansvdLaan** [comment]
Haha, stupid oversight of me. 

Thanks a lot, I will check out the GUI editor.
