### ISSUE TITLE
Running prism-test (prism-auto -tm) on Windows/Cygwin

### ISSUE THREAD

**Issue by davexparker** [prismmodelchecker/prism#11]
Running `prism-test` (or, equivalently, `prism-auto -tm`) on Windows/Cygwin fails like this:

`Error: Couldn't open log file "/tmp/tmpO3RYpV".`

This is because, in test mode, `prism-auto` creates a temporary file and passes it to the `prism` executable via the `-mainlog` switch. On Windows, subprocesses cannot access temporary files created in Python with `tempfile.NamedTemporaryFile(delete=False)`. There is some info and possible solutions here:

http://stackoverflow.com/questions/15169101/how-to-create-a-temporary-file-that-can-be-read-by-a-subprocess/15235559#15235559

but I have not managed to get anything to work yet.

**Comment by kleinj** [comment]
Hi,

have a look at
https://github.com/kleinj/prism-svn/commits/proposed-prism-auto

These 3 commits do the following:
-  On Windows, fallback to the previously used method of redirecting stdout of PRISM to the temporary log file instead of using -mainlog. This won't work with nailgun, but that's not supported on Windows at the moment anyways.
- For the export checks, use "universal newline mode" while comparing the PRISM export and the reference file. This will say that two files that only differ in line endings are equivalent.
- Cleanup the temporary log files used in test mode (not specific to Windows)

With this, I was able to run `prism-auto -tm .` on the test suite successfully under Cygwin.

**Comment by davexparker** [comment]
Thanks Joachim. I've just tested in a Win32 VM with a fresh clone of your branch, and the test suite now runs fine for me. So we are ok to merge that change I would say.

**Comment by kleinj** [comment]
Fixed on the trunk, can be closed.
