### ISSUE TITLE
Cursor placement when clicking character

### ISSUE THREAD

**Issue by ahelwer** [prismmodelchecker/prism#128]
This is somewhat nitpicky so just throwing it out there. In most text editors, clicking a character places the cursor right *before* that character. However, the PRISM editor is the opposite: clicking a character places the cursor *after* that character. This very well might be intended behavior, but it doesn't seem to line up with convention from a number of popular text editors I tested so I thought I'd document it. Feel free to close as wontfix if this is desired.

**Comment by davexparker** [comment]
Hi @ahelwer. I had a look at this when resolving #127. I see what you mean - and it is a bit annoying. It also means that the wrong part of the text is selected when you double click a single character.

It seems that there is a simple fix, namely making the `PrismView` class in `userinterface.model.PrismEditorKit` extend `WrappedPlainView` rather than `PlainView`. But this does change the behaviour of the editor (since it wraps text), so I might make this configurable, with the wrapped view being the default, but I'll do this after the (reasonably imminent) 4.7 release.
