### ISSUE TITLE
PTA: check for timed reachability

### ISSUE THREAD

**Issue by proteusGIT** [prismmodelchecker/prism#136]
we are generating PTA and need to determine all states (given by variable s) that are not reachable due to timing constraints.
```
pta

module M

	s : [0..20] init 0;

	c0 : clock;
	c1 : clock;
	c2 : clock;
	c3 : clock;
(...)
````
As of now, we are checking whether `Pmax=? [ F "s=0" ]` ... `Pmax=? [ F "s=20" ]` have a probability of `>0` but this is not really efficient since the entire check is performed again and again for each state.
Is there a way to check all states for timed reachability at once?
If that would help, we could also remove the probabilism from the PTA to obtain a timed automaton but there seems to be no special support for that in prism. In particular, we are not interested in precise values but only whether the state is reachable and checking for Pmax is certainly more costly that what we need at this stage.

Could you please propose a solution/workaround to this problem?

**Comment by davexparker** [comment]
Hi @proteusGIT. Is the PTA model amenable to analysis with the "digital clocks" engine? i.e. does it have no strict (`c0<5`) or diagonal (`c0<=c1`) clock comparisons? If so, you could generate the corresponding MDP model using `-exportdigital`; see [here](http://prismmodelchecker.org/manual/PropertySpecification/PTAProperties), and then run that model through PRISM to see the full set of reachable states in one pass.

**Comment by proteusGIT** [comment]
Thanks! This sounds really promising.
The comparisons in my file are all of the form "c0<=4" for invariants and "c0>=3" for guards.

However, somehow prism does not generate a file.
The output is as follows.
```
(...):~/prism-4.6-linux64$ ./bin/prism -javamaxmem 300g -javastack 5g  ~/(...)/resulting_pta.nm  -exportdigital ./exportdigital.nm
PRISM
=====

Version: 4.6
Date: Mon Oct 05 13:20:59 CEST 2020
Hostname: (...)
Memory limits: cudd=1g, java(heap)=266.7g
Command line: prism -javamaxmem 300g -javastack 5g /home/(...)/resulting_pta.nm -exportdigital ./exportdigital.nm

Parsing model file "/home/(...)/resulting_pta.nm"...

Type:        PTA
Modules:     M
Variables:   s c0 c1 c2 c3 c4 c5 c6 c7 c8
```
The list of variables looks fine to me.
The file is rather big but prism does not complain about memory problems.
While prism also did not complain about the arguments, I could not find it in the `prism -help` output.

Also, what would be the follow-up call then that you mentioned?

**Comment by davexparker** [comment]
Ah, you need to provide at least some property to be checked, otherwise the digital clocks translation will not actually be triggered. Here's an example, for a built-in model:

`prism ../prism-examples/ptas/firewire/abst/firewire.nm -const delay=3 -pf 'Pmax=?[F s=1]' -ptamethod digital -exportdigital digital.nm`

As for the follow-up call, it depends what you want. If you want to see the full set of reachable states, you could use, for example:

`prism digital.nm -const delay=3 -exportstates digital.sta`

If you want to see the range of values for a variable `s` that are reachable, you could do:

`prism digital.nm -const delay=3 -pf 'filter(range,s)'`

**Comment by proteusGIT** [comment]
Thanks, this really helped me. However, it seems that my PTA are often too big...

**Comment by davexparker** [comment]
Great, And, yes, that (model size) could indeed be an issue. Usually, switching to the MTBDD engine (`-m`) is a promising option for digital clocks models but, since you are checking a non-numerical property (e.g. `filter(range,s)`), I think you are already already effectively using that engine.

I'll mark the issue as closed now.
