### ISSUE TITLE
Buggy state reward export on 32-bit linux

### ISSUE THREAD

**Issue by davexparker** [prismmodelchecker/prism#16]
After the 4.4 release, the test-suite fails on linux32. This seems to be mainly due to the incorrect exporting of state rewards, more specifically, the second number on the first line (number of non-zero values) shows as zero. Examples can be found in `prism-tests/functionality/export/ctmc`.

The likely cause is the call to `DD_GetNumMinterms` on line 69 of `src/mtbdd/PM_ExportVector.cc`, since there was some 32/64-bit CUDD tidying done just prior to 4.4.

**Comment by kleinj** [comment]
This was an interesting bug.

In SVN commit 12019 (https://github.com/prismmodelchecker/prism-svn/commit/1d8f9fc6b9a8ec44ade8f7dbc04b3688f8f95bc5), we converted the ODD indizes from long to int64_t to get the same size in 32/64bit on Linux / OS X and Windows.

With this change, the format string used here became incorrect and, on 32bit Linux, the second "%.0f" printing takes its value from part of the first argument instead of from the double returned by DD_GetNumMinterms, i.e., reading from the wrong memory location, outputting 0.

I pushed a commit to trunk that uses the PRId64 macro to get the correct format string parameter.

I'm currently working on annotating the printf-like functions introduced by PRISM so that the compiler can do their usual format string analysis and produce warnings if we get it wrong.
