### ISSUE TITLE
Location of configuration file on UNIX-like systems

### ISSUE THREAD

**Issue by hentom** [prismmodelchecker/prism#38]
Consider using the the configuration file location as described in the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) as a default on UNIX-like systems. Configuration files as a hidden file in the user directory are annoying and inconsistent with many other applications.

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

**Comment by kleinj** [comment]
Hi,

this seems sensible, looks like more and more applications on Linux actually use this convention.

I guess, if we change the handling to that, it would make sense to also do something similar for Mac OS. There, it looks like `$HOME/Library/Preferences/` seems to be the preferred location.

We'd also need to have support for loading legacy settings, i.e., the current location `$HOME/.prism`. I'd think that forcefully moving the file would not be a good idea, right?

The logic is currently in https://github.com/prismmodelchecker/prism/blob/03d83d4abb5a5a1047863f5afab5db4e8596bd2e/prism/src/prism/PrismSettings.java#L631-L634

If I understand the XDG specs correctly, at a minimum that would mean that we'd have to look in several locations:

1. `$XDG_CONFIG_HOME/prism/prism.settings`
2. `$HOME/.config/prism/prism.settings` (if `XDG_CONFIG_HOME` is not set in the environment)
3. `$HOME/.prism`(legacy location)
 
If any of those files exists, we'd load from there (in that order) and likewise write back. If none of them exist, we'd write to (1) or (2), depending if `XDG_CONFIG_HOME` is set. For `$HOME`,  we'd probably use `System.getProperty("user.home")` as before. For writing, we'd have to ensure that the corresponding directories exist (or are created).

Do we need to support `XDG_CONFIG_DIRS`, i.e., a `PATH`-like list of directories to search for? I guess that's useful for specifying site-wide default configurations (e.g., in `/etc`), but not really necessary for us?

For Mac OS, we'd look at

1. `$HOME/Library/Preferences/prism/prism.settings`
2. `$HOME/.prism`

and for first save would write to (1).

Related: In
https://github.com/prismmodelchecker/prism/blob/03d83d4abb5a5a1047863f5afab5db4e8596bd2e/prism/src/prism/Prism.java#L324
(called on GUI startup), if no settings file is found, it directly writes one with the default settings. Do we want that, or just store once the user has clicked on `Save settings` in the settings dialog?

Another thing: If the locations become more complex (varied due to OS), it might make sense to print a message on loading and saving the settings file into the log with the corresponding path.

**Comment by davexparker** [comment]
Done. Thanks @hentom and @kleinj.

Happy to also consider the other two suggestions (only creating the settings file on save, and printing a message).
